=== taskcluster/taskcluster/services/queue/schemas/0.2.0/task-status-structure.json
{
  "id":           "http://schemas.taskcluster.net/0.2.0/task-status-structure.json#",
  "$schema":      "http://json-schema.org/draft-04/schema#",
  "title":        "Task Status Structure",
  "description":  "Structure holding the state of a task",
  "type":               "object",
  "properties": {
    "task_id":          {"$ref": "http://schemas.taskcluster.net/0.2.0/uuid.json#"},
    "provisioner_id":   {"$ref": "http://schemas.taskcluster.net/0.2.0/identifier.json#"},
    "worker_type":      {"$ref": "http://schemas.taskcluster.net/0.2.0/identifier.json#"},
    "runs":             {"type": "array"},
    "state":            {"enum": ["pending", "running", "completed", "failed"]},
    "reason":           {"type": "string"},
    "routing":          {"type": "string", "maxLength": 64},
    "retries":          {"type": "integer", "minimum": 0, "maximum": 999},
    "priority":         {"type": "number"},
    "created":          {"type": "string", "format": "date-time"},
    "deadline":         {"type": "string", "format": "date-time"},
    "taken_until":      {"type": "string", "format": "date-time"}
  },
  "additionalProperties":   false,
  "required": [
    "task_id", "provisioner_id", "worker_type", "runs", "state", "reason",
    "routing", "retries", "priority", "created", "deadline", "taken_until"
  ]
}

=== taskcluster/taskcluster/services/queue/tests/validation/0.2.0/task-status-structure-succ.json
{
  "task_id":            "70f8926b-c4be-4604-9c33-4e9628bc31f6",
  "provisioner_id":     "jonasfj-test-aws-provisioner",
  "worker_type":        "map-this-to-my-cool-ami",
  "runs":               [],
  "state":              "pending",
  "reason":             "none",
  "routing":            "jonasfjs-precious-tasks.stupid-test.aws",
  "retries":            0,
  "priority":           2.6,
  "created":            "2014-02-01T03:22:36.356Z",
  "deadline":           "2014-03-01T03:22:36.356Z",
  "taken_until":        "1970-01-01T00:00:00.000Z"
}
